export const applicationData = [
  {
    job: "603e1f7a1f1b2c001f8c8e7a",
    applicantName: "John Doe",
    applicantEmail: "john.doe@example.com",
    resume: "https://example.com/resumes/john-doe.pdf",
    coverLetter: "https://example.com/coverletters/john-doe.pdf",
    status: "applied",
    appliedAt: new Date("2023-01-15T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7b",
    applicantName: "Sara Smith",
    applicantEmail: "sara.smith@example.com",
    resume: "https://example.com/resumes/sara-smith.pdf",
    coverLetter: "https://example.com/coverletters/sara-smith.pdf",
    status: "interviewed",
    appliedAt: new Date("2023-02-20T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7c",
    applicantName: "Emily Johnson",
    applicantEmail: "emily.johnson@example.com",
    resume: "https://example.com/resumes/emily-johnson.pdf",
    coverLetter: "",
    status: "offered",
    appliedAt: new Date("2023-03-10T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7d",
    applicantName: "Michael Brown",
    applicantEmail: "michael.brown@example.com",
    resume: "https://example.com/resumes/michael-brown.pdf",
    coverLetter: "https://example.com/coverletters/michael-brown.pdf",
    status: "rejected",
    appliedAt: new Date("2023-04-15T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7e",
    applicantName: "Jessica Taylor",
    applicantEmail: "jessica.taylor@example.com",
    resume: "https://example.com/resumes/jessica-taylor.pdf",
    coverLetter: "",
    status: "applied",
    appliedAt: new Date("2023-05-01T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7f",
    applicantName: "David Wilson",
    applicantEmail: "david.wilson@example.com",
    resume: "https://example.com/resumes/david-wilson.pdf",
    coverLetter: "https://example.com/coverletters/david-wilson.pdf",
    status: "interviewed",
    appliedAt: new Date("2023-06-10T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7g",
    applicantName: "Laura Martin",
    applicantEmail: "laura.martin@example.com",
    resume: "https://example.com/resumes/laura-martin.pdf",
    coverLetter: "",
    status: "offered",
    appliedAt: new Date("2023-07-05T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7h",
    applicantName: "William Anderson",
    applicantEmail: "william.anderson@example.com",
    resume: "https://example.com/resumes/william-anderson.pdf",
    coverLetter: "https://example.com/coverletters/william-anderson.pdf",
    status: "rejected",
    appliedAt: new Date("2023-08-12T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7i",
    applicantName: "Olivia Thomas",
    applicantEmail: "olivia.thomas@example.com",
    resume: "https://example.com/resumes/olivia-thomas.pdf",
    coverLetter: "",
    status: "applied",
    appliedAt: new Date("2023-09-01T10:00:00Z"),
  },
  {
    job: "603e1f7a1f1b2c001f8c8e7j",
    applicantName: "James Jackson",
    applicantEmail: "james.jackson@example.com",
    resume: "https://example.com/resumes/james-jackson.pdf",
    coverLetter: "https://example.com/coverletters/james-jackson.pdf",
    status: "interviewed",
    appliedAt: new Date("2023-09-15T10:00:00Z"),
  },
];
