import dotenv, { configDotenv } from "dotenv";
configDotenv();
export const PORT = process.env.PORT || 3000;
export const MONGO_URI = process.env.MONGO_URI;
export const JWT_SECRET = process.env.JWT_SECRET;
export const BASE_URL = process.env.BASE_URL;
export const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
export const CLOUD_NAME = process.env.CLOUD_NAME;
export const CLOUD_API_KEY = process.env.CLOUD_API_KEY;
export const CLOUD_API_SECRET = process.env.CLOUD_API_SECRET;
